version: '3.8'

services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network  

  api:
    depends_on:
      - mongodb
    build: ./api
    container_name: fastapi-api-container
    ports:
      - "8000:8000"
    networks:
      - app_network
  
  ctkinter_gui:
    depends_on:
      - api
    build: ./ctkinter
    container_name: ctkinter
    command: ["./entrypoint.sh"]
    networks:
      - app_network    

networks:
  app_network:
    name: app_network